import { Router, type Request, type Response } from 'express'
import { connectWorkspace, getSocketStatus, setQrCallback, clearQrCallback } from './socket-manager.js'
import { handleInboundMessage } from './message-handler.js'
import { logger } from './logger.js'

export const qrRouter = Router()

/**
 * GET /qr/:workspaceId — SSE stream that sends QR codes as they are generated.
 *
 * The client opens an EventSource to this endpoint. The server:
 * 1. Starts the Baileys connection for the workspace (if not already connected)
 * 2. If already connected (stored creds), sends { type: "connected" } and closes
 * 3. Otherwise, streams QR codes as { type: "qr", qr: "<base64>" }
 * 4. Sends periodic status updates { type: "status", status: "<status>" }
 * 5. Closes the stream once connected
 */
qrRouter.get('/qr/:workspaceId', async (req: Request, res: Response): Promise<void> => {
  const rawParam = req.params['workspaceId']
  const workspaceId = Array.isArray(rawParam) ? rawParam[0] : rawParam
  if (!workspaceId) {
    res.status(400).json({ error: 'Missing workspaceId' })
    return
  }

  // Set SSE headers
  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')
  res.flushHeaders()

  // Start connection (will generate QR if no stored creds)
  try {
    await connectWorkspace(workspaceId, (msg) => {
      void handleInboundMessage(workspaceId, msg)
    })
  } catch (err) {
    logger.error({ workspaceId, err }, 'Failed to start connection')
    res.write(
      `data: ${JSON.stringify({ type: 'error', message: 'Failed to connect' })}\n\n`
    )
    res.end()
    return
  }

  // Check if already connected (had stored creds)
  const { status } = getSocketStatus(workspaceId)
  if (status === 'connected') {
    res.write(`data: ${JSON.stringify({ type: 'connected' })}\n\n`)
    res.end()
    return
  }

  // Stream QR codes as they are generated by Baileys
  setQrCallback(workspaceId, (qr: string) => {
    res.write(`data: ${JSON.stringify({ type: 'qr', qr })}\n\n`)
  })

  // Periodic status updates — close when connected
  const STATUS_POLL_INTERVAL_MS = 2000
  const statusInterval = setInterval(() => {
    const { status: currentStatus } = getSocketStatus(workspaceId)
    res.write(
      `data: ${JSON.stringify({ type: 'status', status: currentStatus })}\n\n`
    )

    if (currentStatus === 'connected') {
      clearInterval(statusInterval)
      clearQrCallback(workspaceId)
      res.end()
    }
  }, STATUS_POLL_INTERVAL_MS)

  // Clean up on client disconnect — clear QR callback to prevent writes to closed response
  req.on('close', () => {
    clearInterval(statusInterval)
    clearQrCallback(workspaceId)
  })
})
